- name: AVI Login
  set_fact:
    avi_login: &avi_login
      controller: "lab4-nsxalbc-1.harrythambi.cloud"
      username: "admin"
      password: "VMware1!VMware1!"
      api_version: "22.1.3"

- name: Create a vsvip for VMware Cloud Director
  delegate_to: localhost
  avi_api_session:
    <<: *avi_login
    http_method: post
    path: vsvip
    data:
      name: vsvip-10.1.183.31
      vip:
          - ip_address:
              addr: 10.1.183.31
              type: V4
            prefix_length: 32
            vip_id: 1
            auto_allocate_ip: false
      tenant_ref: '/api/tenant?name=admin'
      cloud_ref: '/api/cloud?name=lab4-NSXT-Cloud'
      tier1_lr: '/infra/tier-1s/lab4-t1-management'
      vrf_context_ref: '/api/vrfcontext?name=lab4-t1-management'