- name: AVI Login
  set_fact:
    avi_login: &avi_login
      controller: "lab4-nsxalbc-1.harrythambi.cloud"
      username: "admin"
      password: "VMware1!VMware1!"
      api_version: "22.1.3"

- name: Create a virtualservice for VMware Cloud Director
  delegate_to: localhost
  avi_api_session:
    <<: *avi_login
    http_method: post
    path: virtualservice
    data:
      name: vs-vcd
      vsvip_ref: '/api/vsvip?name=vsvip-10.1.183.31'
      pool_ref: '/api/pool?name=vcdpool'
      application_profile_ref: '/api/applicationprofile?name=System-L4-Application'
      services:
        - port: 443
          enable_ssl: false
      tenant_ref: '/api/tenant?name=admin'
      cloud_ref: '/api/cloud?name=lab4-NSXT-Cloud'
      tier1_lr: '/infra/tier-1s/lab4-t1-management'
      vrf_context_ref: '/api/vrfcontext?name=lab4-t1-management'
