- name: AVI Login
  set_fact:
    avi_login: &avi_login
      controller: "lab4-nsxalbc-1.harrythambi.cloud"
      username: "admin"
      password: "VMware1!VMware1!"
      api_version: "22.1.3"


- name: Create a Pool for VMware Cloud Director
  delegate_to: localhost
  avi_api_session:
    <<: *avi_login
    http_method: post
    path: pool
    data:
      name: vcdpool
      description: vcdpool
      health_monitor_refs:
          - '/api/healthmonitor?name=System-TCP'
      servers:
          - hostname: lab4-vcd-1.harrythambi.cloud
            ip:
              addr: 10.10.2.20
              type: V4
      tenant_ref: '/api/tenant?name=admin'
      cloud_ref: '/api/cloud?name=lab4-NSXT-Cloud'
      tier1_lr: '/infra/tier-1s/lab4-t1-management'